## Pipeline de pré-processamento dos reviews do AirBnB, nas cidades de Lisboa e Rio de Janeiro, afim de pesquisa em Text mining pra uma tese de Mestrado em Ciência de dados.

- Universidade Européia
- Mestrado em Ciência de dados e Análise de Negócios
- Orientaora: Prof. Marina Cavique
- Autora: Gisele Maciel da Silva

### Fonte: https://insideairbnb.com/get-the-data/

Datasets:
- reviews.csv **(Rio de Janeiro)** snapshot: 26 September, 2025
- reviews.csv **(Lisboa)** snapshot: 21 September, 2025

In [1]:
# ==========================================
# Importação das bibliotecas necessárias
# ==========================================
import pandas as pd
from langdetect import detect, LangDetectException # Detecta a língua do texto
import matplotlib.pyplot as plt
from collections import Counter
import re
import spacy
from spacy.lang.pt.stop_words import STOP_WORDS
import string
import seaborn as sns

In [2]:
# ==========================================
# mostra o texto completo em cada célula
# ==========================================
pd.set_option("display.max_colwidth", None)

-----
## **Pré-processamento na língua portuguesa**
---------

-------------------
## **Importação do dataset dos reviews da plataforma AirBnB:<br><br>Cidade: Rio de Janeiro.**

------------------

In [3]:
# ==========================================
# Abrir o dataset do Rio de Janeiro na versão filtrada para português
# ==========================================
df_RJ_pt = pd.read_pickle("reviews_RJ_pt.pkl")
df_RJ_pt.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments,cidade,lang
17,17878,597736,2011-10-04,989464,Jose Mauro,"Muito Melhor do que ir para um hotel. Apt com excelente localização( 1 quarteirão da praia), muito organizado e limpo. O proprietário sempre muito solicito para resolver qualquer problema. O Apt também tem um terraço maravilhoso. Esta é a melhor maneira de conhecer o RIO\r<br/>\r<br/>",Rio de Janeiro,pt
18,17878,620065,2011-10-11,1157847,Gabriel,"Muito bom o apartamento, a pouco mais de uma quadra da praia e com muitos lugares para comer e sair por perto.",Rio de Janeiro,pt
34,248756,3425364,2013-01-28,4175433,Nelson,"O apartamento é maravilhoso, novo, bem decorado, muito bem equipado, possui tudo que se precisa. A localização é perfeita próxima a tudo, tanto de Copacabana quanto Ipanema. Quero agradecer a atenção do Bernardo durante a negociação e a simpatia e presteza da Vera como anfitriã. Toda minha família se sentiu acolhida e bem a vontade. Um abraço pra todos e com certeza recomendo este apartamento, como também me hospedarei novamente nele de volta ao Rio.",Rio de Janeiro,pt
36,248756,3620482,2013-02-26,4781492,Rui Nuno,"Excelente apartamento, com ótimas condições e muito bem localizado. Fica perto de tudo - praias, supermercado, padaria, metro e festa - e está muito bem decorado. Recomendamos claramente. Fomos fantasticamente recebidos e deram-nos boas dicas para visitar a cidade. Só ficámos duas noites, mas valeu bem.\r<br/>Obrigado por tudo e sejam felizes.",Rio de Janeiro,pt
40,248756,4272123,2013-04-23,4893381,Isabella,"Dias Maravilhosos! Ap. muito bem decorado e com ótima localização, tudo como combinado. Recomendo!",Rio de Janeiro,pt

In [4]:
# ==========================================
# Verificar valores nulos
# ==========================================
print("Valores nulos por coluna:\n", df_RJ_pt.isnull().sum())

Valores nulos por coluna:
 listing_id       0
id               0
date             0
reviewer_id      0
reviewer_name    2
comments         0
cidade           0
lang             0
dtype: int64

In [5]:
# ==========================================
# Conta quantas linhas duplicadas existem no dataset filtrado para português
# ==========================================
print("Número de linhas duplicadas:", df_RJ_pt.duplicated().sum())

Número de linhas duplicadas: 0

In [181]:
df_RJ_pt.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments,cidade,lang,char_count,word_count
17,17878,597736,2011-10-04,989464,Jose Mauro,"Muito Melhor do que ir para um hotel. Apt com excelente localização( 1 quarteirão da praia), muito organizado e limpo. O proprietário sempre muito solicito para resolver qualquer problema. O Apt também tem um terraço maravilhoso. Esta é a melhor maneira de conhecer o RIO\r<br/>\r<br/>",Rio de Janeiro,pt,283,47
18,17878,620065,2011-10-11,1157847,Gabriel,"Muito bom o apartamento, a pouco mais de uma quadra da praia e com muitos lugares para comer e sair por perto.",Rio de Janeiro,pt,111,22
34,248756,3425364,2013-01-28,4175433,Nelson,"O apartamento é maravilhoso, novo, bem decorado, muito bem equipado, possui tudo que se precisa. A localização é perfeita próxima a tudo, tanto de Copacabana quanto Ipanema. Quero agradecer a atenção do Bernardo durante a negociação e a simpatia e presteza da Vera como anfitriã. Toda minha família se sentiu acolhida e bem a vontade. Um abraço pra todos e com certeza recomendo este apartamento, como também me hospedarei novamente nele de volta ao Rio.",Rio de Janeiro,pt,454,75
36,248756,3620482,2013-02-26,4781492,Rui Nuno,"Excelente apartamento, com ótimas condições e muito bem localizado. Fica perto de tudo - praias, supermercado, padaria, metro e festa - e está muito bem decorado. Recomendamos claramente. Fomos fantasticamente recebidos e deram-nos boas dicas para visitar a cidade. Só ficámos duas noites, mas valeu bem.\r<br/>Obrigado por tudo e sejam felizes.",Rio de Janeiro,pt,345,52
40,248756,4272123,2013-04-23,4893381,Isabella,"Dias Maravilhosos! Ap. muito bem decorado e com ótima localização, tudo como combinado. Recomendo!",Rio de Janeiro,pt,98,14

-----
## **Função única de limpeza textual para remover quebras de linhas, tags HTML e números que atrapalham a semântica do texto.**
------

In [18]:
# ==========================================
# Função única de limpeza textual
# ==========================================
nlp = spacy.load("pt_core_news_lg")

def limpar_texto(texto):
    texto = str(texto)

    # Remover quebras de linha e tags HTML simples
    texto = texto.replace("\\r<br/>", " ")
    texto = texto.replace("<br/>", " ")
    
    # Remover tags HTML genéricas
    texto = re.sub(r"<.*?>", " ", texto)

    # Remover parênteses
    texto = texto.replace("(", " - ").replace(")", " - ")

    # Acrescentar espaço depois da pontuação, se não houver
    texto = re.sub(r"(?<=[.,;:!?])(?=\S)", " ", texto)

    # Remover números
    texto = re.sub(r"\d+", " ", texto)

    # Remover espaços múltiplos
    texto = re.sub(r"\s+", " ", texto)

    return texto.strip()

In [19]:
df_RJ_pt["texto_limpo"] = df_RJ_pt["comments"].apply(limpar_texto)
df_RJ_pt.head(20)

,listing_id,id,date,reviewer_id,reviewer_name,comments,cidade,lang,texto_limpo
17,17878,597736,2011-10-04,989464,Jose Mauro,"Muito Melhor do que ir para um hotel. Apt com excelente localização( 1 quarteirão da praia), muito organizado e limpo. O proprietário sempre muito solicito para resolver qualquer problema. O Apt também tem um terraço maravilhoso. Esta é a melhor maneira de conhecer o RIO\r<br/>\r<br/>",Rio de Janeiro,pt,"Muito Melhor do que ir para um hotel. Apt com excelente localização - quarteirão da praia - , muito organizado e limpo. O proprietário sempre muito solicito para resolver qualquer problema. O Apt também tem um terraço maravilhoso. Esta é a melhor maneira de conhecer o RIO"
18,17878,620065,2011-10-11,1157847,Gabriel,"Muito bom o apartamento, a pouco mais de uma quadra da praia e com muitos lugares para comer e sair por perto.",Rio de Janeiro,pt,"Muito bom o apartamento, a pouco mais de uma quadra da praia e com muitos lugares para comer e sair por perto."
34,248756,3425364,2013-01-28,4175433,Nelson,"O apartamento é maravilhoso, novo, bem decorado, muito bem equipado, possui tudo que se precisa. A localização é perfeita próxima a tudo, tanto de Copacabana quanto Ipanema. Quero agradecer a atenção do Bernardo durante a negociação e a simpatia e presteza da Vera como anfitriã. Toda minha família se sentiu acolhida e bem a vontade. Um abraço pra todos e com certeza recomendo este apartamento, como também me hospedarei novamente nele de volta ao Rio.",Rio de Janeiro,pt,"O apartamento é maravilhoso, novo, bem decorado, muito bem equipado, possui tudo que se precisa. A localização é perfeita próxima a tudo, tanto de Copacabana quanto Ipanema. Quero agradecer a atenção do Bernardo durante a negociação e a simpatia e presteza da Vera como anfitriã. Toda minha família se sentiu acolhida e bem a vontade. Um abraço pra todos e com certeza recomendo este apartamento, como também me hospedarei novamente nele de volta ao Rio."
36,248756,3620482,2013-02-26,4781492,Rui Nuno,"Excelente apartamento, com ótimas condições e muito bem localizado. Fica perto de tudo - praias, supermercado, padaria, metro e festa - e está muito bem decorado. Recomendamos claramente. Fomos fantasticamente recebidos e deram-nos boas dicas para visitar a cidade. Só ficámos duas noites, mas valeu bem.\r<br/>Obrigado por tudo e sejam felizes.",Rio de Janeiro,pt,"Excelente apartamento, com ótimas condições e muito bem localizado. Fica perto de tudo - praias, supermercado, padaria, metro e festa - e está muito bem decorado. Recomendamos claramente. Fomos fantasticamente recebidos e deram-nos boas dicas para visitar a cidade. Só ficámos duas noites, mas valeu bem. Obrigado por tudo e sejam felizes."
40,248756,4272123,2013-04-23,4893381,Isabella,"Dias Maravilhosos! Ap. muito bem decorado e com ótima localização, tudo como combinado. Recomendo!",Rio de Janeiro,pt,"Dias Maravilhosos! Ap. muito bem decorado e com ótima localização, tudo como combinado. Recomendo!"
41,248756,5662504,2013-07-10,6859166,Ligia,"Excelente localização, muito perto da praia e fácil acesso para outros pontos. Fomos muito bem recebidos, nossa anfitriã foi muito atenciosa na nossa chegada e durante a estadia. Tudo funcionou muito bem (TV, internet, etc) e nos sentimos em casa.\r<br/>Ponto de atenção: a rua é bastante movimentada, então pode haver um pouco de barulho vindo da rua à noite. Para quem não se incomoda, não atrapalha.\r<br/>",Rio de Janeiro,pt,"Excelente localização, muito perto da praia e fácil acesso para outros pontos. Fomos muito bem recebidos, nossa anfitriã foi muito atenciosa na nossa chegada e durante a estadia. Tudo funcionou muito bem - TV, internet, etc - e nos sentimos em casa. Ponto de atenção: a rua é bastante movimentada, então pode haver um pouco de barulho vindo da rua à noite. Para quem não se incomoda, não atrapalha."
42,248756,5789290,2013-07-16,5693647,Victor Hugo,"Apartamento muito bom, LIMPO e bem organizado. Fui bem recepcionado e tive um fim de semana muito agradável.",Rio de Janeiro,pt,"Apartamento muito bom, LIMPO e bem organizado. Fui bem recepcionado e tive um fim de semana muito agradável."
43,248756,5966623,2013-07-24,6591097,Rosilene,"A localização é excelente e muito perto da praia. A Vera (a anfitriã) é uma pessoa muito atenciosa e nos orientou em vários passeios. O apartamento é lindo e muito aconchegante, exatamente como aparece nas fotos.\r<br/>Fomos muito bem recebidos, valeu a pena... o Rio de Janeiro é maravilhoso!!! \r<br/>Grata Vera pelo carinho, pena que passou rápido.",Rio de Janeiro,pt,"A localização é excelente e muito perto da praia. A Vera - a anfitriã - é uma pessoa muito atenciosa e nos orientou em vários passeios. O apartamento é lindo e muito aconchegante, exatamente como aparece nas fotos. Fomos muito bem recebidos, valeu a pena. . . o Rio de Janeiro é maravilhoso! ! ! Grata Vera pelo carinho, pena que passou rápido."
45,248756,6657707,2013-08-20,726455,Daniela,"Excelente!!! Ha 1 quarteirão da praia, localizado perto de tudo, muito seguro. Local muito limpo e organizado, agrada a todos os gostos! Não tenho nenhuma reclamação! Aproveitamos e recomendamos!!",Rio de Janeiro,pt,"Excelente! ! ! Ha quarteirão da praia, localizado perto de tudo, muito seguro. Local muito limpo e organizado, agrada a todos os gostos! Não tenho nenhuma reclamação! Aproveitamos e recomendamos! !"
52,248756,30378171,2015-04-21,21457685,Rodrigo,"Este apartamento em Copacabana é excelente e superou minhas expectativas, sua localização é ótima, a higiene assim como a comodidade são muito boas, espero poder voltar outras vezes. A anfitriã Vera que nos recepcionou foi muito atenciosa e nos indicou muitos pontos para visitas, agradeço a todos pelo excelente trabalho.",Rio de Janeiro,pt,"Este apartamento em Copacabana é excelente e superou minhas expectativas, sua localização é ótima, a higiene assim como a comodidade são muito boas, espero poder voltar outras vezes. A anfitriã Vera que nos recepcionou foi muito atenciosa e nos indicou muitos pontos para visitas, agradeço a todos pelo excelente trabalho."
53,248756,34371908,2015-06-07,23447187,Rodrigo,Bernardo e Vera nos receberam de forma incrível. O apartamento é até melhor do que nas fotos! esperamos voltar!,Rio de Janeiro,pt,Bernardo e Vera nos receberam de forma incrível. O apartamento é até melhor do que nas fotos! esperamos voltar!
56,248756,38400514,2015-07-15,2282410,Graziela,Obrigada esta tudo perfeito!!!,Rio de Janeiro,pt,Obrigada esta tudo perfeito! ! !
60,248756,51125633,2015-10-18,41157789,Samuel,"Rio de Janeiro, cidade maravilhosa...adorei a cidade, as praias, pão de açúcar, corcovado, a casa...essa casa é bonita, tal e qual as fotos, óptima localização junto ao posto 5 de Copacabana, pertinho de Ipanema, limpa, bem decorada, rua cheia de comércio, muito legal. O Bernardo foi muito gentil, respondeu sempre na hora às mensagens, a Vera foi quem me recebeu na casa, uma simpatia, muito prestável e óptima conselheira. Se voltar ao Rio, será aqui que vou ficar. Obrigado por tudo.",Rio de Janeiro,pt,"Rio de Janeiro, cidade maravilhosa. . . adorei a cidade, as praias, pão de açúcar, corcovado, a casa. . . essa casa é bonita, tal e qual as fotos, óptima localização junto ao posto de Copacabana, pertinho de Ipanema, limpa, bem decorada, rua cheia de comércio, muito legal. O Bernardo foi muito gentil, respondeu sempre na hora às mensagens, a Vera foi quem me recebeu na casa, uma simpatia, muito prestável e óptima conselheira. Se voltar ao Rio, será aqui que vou ficar. Obrigado por tudo."
62,248756,58530726,2016-01-03,42918242,Diego,"Bernardo não pode nos receber, Vera que nos receber maravilhosamente bem uma pessoa educada, mto alegre e disposta a explicar tudo sobre o apto, se colocou a disposição para qualquer problema ou necessidade para duvidas. O Apartamento é extremamente maravilhoso (identico as fotos), aplo e com mto espaço e ar condicionado em todos os comodos e com todos utensilios de uma casa completa. Bem localizado, um quarteirao a praia, com diversas possibilidades de restaurantes,Bancos, mercados e farmácias. Devido a sua localização não precisamos utilizar automóvel em nossos passeios O predio e super familiar e tranquilo. Bernardo nos deu atenção antes, durante e depois da estadia ele e muito Claro e objetivo nas resposta.Foi uma otima escolha para passarmos a virada de Ano.",Rio de Janeiro,pt,"Bernardo não pode nos receber, Vera que nos receber maravilhosamente bem uma pessoa educada, mto alegre e disposta a explicar tudo sobre o apto, se colocou a disposição para qualquer problema ou necessidade para duvidas. O Apartamento é extremamente maravilhoso - identico as fotos - , aplo e com mto espaço e ar condicionado em todos os comodos e com todos utensilios de uma casa completa. Bem localizado, um quarteirao a praia, com diversas possibilidades de restaurantes, Bancos, mercados e farmácias. Devido a sua localização não precisamos utilizar automóvel em nossos passeios O predio e super familiar e tranquilo. Bernardo nos deu atenção antes, durante e depois da estadia ele e muito Claro e objetivo nas resposta. Foi uma otima escolha para passarmos a virada de Ano."
70,248756,69543090,2016-04-11,12620220,Silvia,"Super recomendo! Apartamento idêntico às fotos, limpo, organizado e super bem localizado. A Vera, responsável pelo apto, muito querida e prestativa ( nos indicou lugares para ir, qual linha de metrô pegarmos, etc). Quero voltar em breve!",Rio de Janeiro,pt,"Super recomendo! Apartamento idêntico às fotos, limpo, organizado e super bem localizado. A Vera, responsável pelo apto, muito querida e prestativa - nos indicou lugares para ir, qual linha de metrô pegarmos, etc - . Quero voltar em breve!"
72,248756,71381083,2016-04-25,13124979,Ulrico,"Foi muito bem recebido da Vera. O apartamento superou minha expectativas, os quartos são muito melhores que nas fotos. A localização é ótima fica a uma quadra da praia. Com certeza vou querer ficar neste apartamento na próxima vez que vou para Rio!",Rio de Janeiro,pt,"Foi muito bem recebido da Vera. O apartamento superou minha expectativas, os quartos são muito melhores que nas fotos. A localização é ótima fica a uma quadra da praia. Com certeza vou querer ficar neste apartamento na próxima vez que vou para Rio!"
77,248756,101651193,2016-09-14,19862380,Célia Regina,"Fomos recepcionados pela Vera que se mostrou super atenciosa e pronta para qualquer eventualidade. Apartamento como descrito no anúncio, super agradável, limpo e com todas as comodidades necessárias a estadia.\r<br/>Localização excelente, perto de estação de metro, ônibus, supermercados, praias e para passeios a pé. Portaria 24 h. Fomos em 2 casais e é um apartamento que indicamos.",Rio de Janeiro,pt,"Fomos recepcionados pela Vera que se mostrou super atenciosa e pronta para qualquer eventualidade. Apartamento como descrito no anúncio, super agradável, limpo e com todas as comodidades necessárias a estadia. Localização excelente, perto de estação de metro, ônibus, supermercados, praias e para passeios a pé. Portaria h. Fomos em casais e é um apartamento que indicamos."
78,248756,102873716,2016-09-19,45552166,Lidiane,"Minha hospedagem ocorreu no período de 14/09/2016 à 19/09/2016 nesse apartamento que é uma graça. Confortável, aconchegante, tem de tudo para o viajante e é super bem localizado. Vera, a anfitriã, foi super receptiva e atenciosa. Voltarei mais vezes!! Recomendo!!",Rio de Janeiro,pt,"Minha hospedagem ocorreu no período de / / à / / nesse apartamento que é uma graça. Confortável, aconchegante, tem de tudo para o viajante e é super bem localizado. Vera, a anfitriã, foi super receptiva e atenciosa. Voltarei mais vezes! ! Recomendo! !"
80,248756,107659782,2016-10-11,63788145,Lucas,"Deu tudo certo, Bernardo e a Vera sempre disponíveis e fáceis de comunicar.",Rio de Janeiro,pt,"Deu tudo certo, Bernardo e a Vera sempre disponíveis e fáceis de comunicar."
81,248756,108806937,2016-10-17,10648406,Bárbara,"Ficamos entre dois casais, ambos de trinta e poucos anos, sem crianças, e adoramos o apartamento! Em prédio tranquilo, bem localizado, aconchegante, espaçoso, bem decorado e super bem equipado com tudo de que precisamos. Toalhas e roupas de cama cheirosas e macias. Travesseiros de pena e colchões para todos os gostos, o de um dos quartos mais duro e o outro mais mole. Acervo de cds maravilhoso! :) Única coisa a levar em consideração, caso goste de tirar sonecas fora de hora e seu sono seja leve, o apartamento é de frente para a avenida, então tem barulho de trânsito e de rua, mas nada que, na minha opinião, não tenha compensado todo o resto que é top!",Rio de Janeiro,pt,"Ficamos entre dois casais, ambos de trinta e poucos anos, sem crianças, e adoramos o apartamento! Em prédio tranquilo, bem localizado, aconchegante, espaçoso, bem decorado e super bem equipado com tudo de que precisamos. Toalhas e roupas de cama cheirosas e macias. Travesseiros de pena e colchões para todos os gostos, o de um dos quartos mais duro e o outro mais mole. Acervo de cds maravilhoso! : - Única coisa a levar em consideração, caso goste de tirar sonecas fora de hora e seu sono seja leve, o apartamento é de frente para a avenida, então tem barulho de trânsito e de rua, mas nada que, na minha opinião, não tenha compensado todo o resto que é top!"

In [20]:
# ==========================================
# Salva o DataFrame pré-processado em um arquivo pickle, para uso posterior
# ==========================================    
df_RJ_pt.to_pickle("Reviews_RJ_texto_limpo.pkl")

-------------------
## **Importação do dataset dos reviews da plataforma AirBnB:<br><br>Cidade: Lisboa.**

------------------

In [31]:
# ==========================================
# Importar os datasets "reviews_Lisboa_pt.pkl" da cidade de Lisboa
# ==========================================
df_Lisboa_pt = pd.read_pickle("reviews_Lisboa_pt.pkl")
df_Lisboa_pt.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments,cidade,lang
0,1113142,60014456,2016-01-18,35314589,Andre,Adoramos o lugar. Muito bem localizado e prático. Fomos muito bem recepcionados pela Inês que nos prestou toda a assistência necessária.,Lisboa,pt
4,1113142,215013241,2017-11-27,154490966,Agenor,Apartamento muito bom. Anfitrião atencioso e solícito. Não tenho qualquer reclamação. Só elogios.,Lisboa,pt
6,1113142,577387176,2019-12-15,15145286,Nath,"O apartamento é bem localizado e tem os utensílios para uma estadia mais prolongada. No entanto, tive sérios problemas com o proprietário : mudaram a data do meu check in no dia que eu cheguei - eu viajei com toda minha família e tenho um bebe com menos de 2 anos. Há quedas correntes de energia. E a proprietária me cobrou de algo absurdo: o vidro do box que protege a área de banho se trincou sozinho. Poderia ter causado um enorme acidente ao meu filho e demais membros da família. E a proprietária insiste em me cobrar o valor como se eu ou alguém tivéssemos feito algo. Um técnico foi ao local e confirmou que isso acontecia com o tempo, fiz até um video do vidro se despedaçando. Quase nao dormi preocupada com meu filho e quando achei que merecia um pedido de ""desculpas"",. veio uma cobrança. Muito absurdo.",Lisboa,pt
12,6499,18879225,2014-09-02,17027029,Simone,"Ola Bruno,\r<br/>\r<br/>Tive um mes Fantástico em seu apartamento. O apartamento realmente está bem situado. Um elétrico passa a cada 15 min. em frente, bem como várias linhas de autocarro. Isto facilita para ir ao Centro de Lisboa. Pontos turísticos e restaurantes bem próximos.\r<br/>Apartamento aconchegante com facilidade em organizá-lo. Ótimo acesso a internet. Boa vizinhança.\r<br/>Sempre tive apoio do anfitriao Bruno, bem como otima comunicao online. Esteve sempre auxiliando e buscou resolver de imediato coisas inesperadas no apartamento.\r<br/>\r<br/>Obrigado! Até à próxima oportunidade de estar em Lisboa.",Lisboa,pt
13,6499,21074122,2014-10-11,7661611,Cláudio,"Encontramos o apartamento de Bruno exatamente conforme a descrição e as fotos, além de muito bem limpo, cuidado com muito carinho e equipado com tudo o que é necessário e prático. Lençóis e toalhas disponíveis, travesseiros e uma cama extremamente confortável. A localização é incrível, segura e perfeita para visitar Lisboa. Todos os monumentos e locais históricos de Belém estão a alguns minutos da caminhada mais agradável da cidade, em meio a jardins, praças e restaurantes, e muitas opções de transportes para as outras zonas estão à porta do prédio. Numa estada mais extensa, como a nossa, é importante que o anfitrião esteja sempre ao alcance, e a atenção e a disponibilidade de Bruno realmente impressionam. Nenhuma de nossas comunicações e nenhum pequeno ajuste ou providência que foi necessária demorou mais do que alguns minutos. Uma de nossas melhores experiências no AirBnb.",Lisboa,pt

In [32]:
# ==========================================
# Verificar valores nulos
# ==========================================
print("Valores nulos por coluna:\n", df_Lisboa_pt.isnull().sum())

Valores nulos por coluna:
 listing_id       0
id               0
date             0
reviewer_id      0
reviewer_name    3
comments         0
cidade           0
lang             0
dtype: int64

In [33]:
# ==========================================
# Conta quantas linhas duplicadas existem no dataset filtrado para português
# ==========================================
print("Número de linhas duplicadas:", df_Lisboa_pt.duplicated().sum())

Número de linhas duplicadas: 0

-----
## **Função única de limpeza textual para remover quebras de linhas, tags HTML, números, pontuação e caracteres especiais que atrapalham a semântica do texto.**
------

In [29]:
# ==========================================
# Função única de limpeza textual
# ==========================================
nlp = spacy.load("pt_core_news_lg")

def limpar_texto(texto):
    texto = str(texto)

    # Remover quebras de linha e tags HTML simples
    texto = texto.replace("\\r<br/>", " ")
    texto = texto.replace("<br/>", " ")
    
    # Remover tags HTML genéricas
    texto = re.sub(r"<.*?>", " ", texto)

    # Remover parênteses
    texto = texto.replace("(", " - ").replace(")", " - ")

    # Acrescentar espaço depois da pontuação, se não houver
    texto = re.sub(r"(?<=[.,;:!?])(?=\S)", " ", texto)

    # Remover números
    texto = re.sub(r"\d+", " ", texto)

    # Remover espaços múltiplos
    texto = re.sub(r"\s+", " ", texto)

    return texto.strip()

In [34]:
df_Lisboa_pt["texto_limpo"] = df_Lisboa_pt["comments"].apply(limpar_texto)
df_Lisboa_pt.head(20)

,listing_id,id,date,reviewer_id,reviewer_name,comments,cidade,lang,texto_limpo
0,1113142,60014456,2016-01-18,35314589,Andre,Adoramos o lugar. Muito bem localizado e prático. Fomos muito bem recepcionados pela Inês que nos prestou toda a assistência necessária.,Lisboa,pt,Adoramos o lugar. Muito bem localizado e prático. Fomos muito bem recepcionados pela Inês que nos prestou toda a assistência necessária.
4,1113142,215013241,2017-11-27,154490966,Agenor,Apartamento muito bom. Anfitrião atencioso e solícito. Não tenho qualquer reclamação. Só elogios.,Lisboa,pt,Apartamento muito bom. Anfitrião atencioso e solícito. Não tenho qualquer reclamação. Só elogios.
6,1113142,577387176,2019-12-15,15145286,Nath,"O apartamento é bem localizado e tem os utensílios para uma estadia mais prolongada. No entanto, tive sérios problemas com o proprietário : mudaram a data do meu check in no dia que eu cheguei - eu viajei com toda minha família e tenho um bebe com menos de 2 anos. Há quedas correntes de energia. E a proprietária me cobrou de algo absurdo: o vidro do box que protege a área de banho se trincou sozinho. Poderia ter causado um enorme acidente ao meu filho e demais membros da família. E a proprietária insiste em me cobrar o valor como se eu ou alguém tivéssemos feito algo. Um técnico foi ao local e confirmou que isso acontecia com o tempo, fiz até um video do vidro se despedaçando. Quase nao dormi preocupada com meu filho e quando achei que merecia um pedido de ""desculpas"",. veio uma cobrança. Muito absurdo.",Lisboa,pt,"O apartamento é bem localizado e tem os utensílios para uma estadia mais prolongada. No entanto, tive sérios problemas com o proprietário : mudaram a data do meu check in no dia que eu cheguei - eu viajei com toda minha família e tenho um bebe com menos de anos. Há quedas correntes de energia. E a proprietária me cobrou de algo absurdo: o vidro do box que protege a área de banho se trincou sozinho. Poderia ter causado um enorme acidente ao meu filho e demais membros da família. E a proprietária insiste em me cobrar o valor como se eu ou alguém tivéssemos feito algo. Um técnico foi ao local e confirmou que isso acontecia com o tempo, fiz até um video do vidro se despedaçando. Quase nao dormi preocupada com meu filho e quando achei que merecia um pedido de ""desculpas"", . veio uma cobrança. Muito absurdo."
12,6499,18879225,2014-09-02,17027029,Simone,"Ola Bruno,\r<br/>\r<br/>Tive um mes Fantástico em seu apartamento. O apartamento realmente está bem situado. Um elétrico passa a cada 15 min. em frente, bem como várias linhas de autocarro. Isto facilita para ir ao Centro de Lisboa. Pontos turísticos e restaurantes bem próximos.\r<br/>Apartamento aconchegante com facilidade em organizá-lo. Ótimo acesso a internet. Boa vizinhança.\r<br/>Sempre tive apoio do anfitriao Bruno, bem como otima comunicao online. Esteve sempre auxiliando e buscou resolver de imediato coisas inesperadas no apartamento.\r<br/>\r<br/>Obrigado! Até à próxima oportunidade de estar em Lisboa.",Lisboa,pt,"Ola Bruno, Tive um mes Fantástico em seu apartamento. O apartamento realmente está bem situado. Um elétrico passa a cada min. em frente, bem como várias linhas de autocarro. Isto facilita para ir ao Centro de Lisboa. Pontos turísticos e restaurantes bem próximos. Apartamento aconchegante com facilidade em organizá-lo. Ótimo acesso a internet. Boa vizinhança. Sempre tive apoio do anfitriao Bruno, bem como otima comunicao online. Esteve sempre auxiliando e buscou resolver de imediato coisas inesperadas no apartamento. Obrigado! Até à próxima oportunidade de estar em Lisboa."
13,6499,21074122,2014-10-11,7661611,Cláudio,"Encontramos o apartamento de Bruno exatamente conforme a descrição e as fotos, além de muito bem limpo, cuidado com muito carinho e equipado com tudo o que é necessário e prático. Lençóis e toalhas disponíveis, travesseiros e uma cama extremamente confortável. A localização é incrível, segura e perfeita para visitar Lisboa. Todos os monumentos e locais históricos de Belém estão a alguns minutos da caminhada mais agradável da cidade, em meio a jardins, praças e restaurantes, e muitas opções de transportes para as outras zonas estão à porta do prédio. Numa estada mais extensa, como a nossa, é importante que o anfitrião esteja sempre ao alcance, e a atenção e a disponibilidade de Bruno realmente impressionam. Nenhuma de nossas comunicações e nenhum pequeno ajuste ou providência que foi necessária demorou mais do que alguns minutos. Uma de nossas melhores experiências no AirBnb.",Lisboa,pt,"Encontramos o apartamento de Bruno exatamente conforme a descrição e as fotos, além de muito bem limpo, cuidado com muito carinho e equipado com tudo o que é necessário e prático. Lençóis e toalhas disponíveis, travesseiros e uma cama extremamente confortável. A localização é incrível, segura e perfeita para visitar Lisboa. Todos os monumentos e locais históricos de Belém estão a alguns minutos da caminhada mais agradável da cidade, em meio a jardins, praças e restaurantes, e muitas opções de transportes para as outras zonas estão à porta do prédio. Numa estada mais extensa, como a nossa, é importante que o anfitrião esteja sempre ao alcance, e a atenção e a disponibilidade de Bruno realmente impressionam. Nenhuma de nossas comunicações e nenhum pequeno ajuste ou providência que foi necessária demorou mais do que alguns minutos. Uma de nossas melhores experiências no AirBnb."
14,6499,24704004,2015-01-02,20348870,Rodrigo,"Estivemos em Lisboa por aproximadamente 03 (três) meses. Durante o período, Bruno se mostrou um excelente anfitrião, bastante solícito e resolutivo, nos atendendo prontamente. O apartamento é aconchegante e dispôs do que precisávamos, ou seja, correspondeu todas as nossas expectativas. O apartamento é muito bem localizado, tendo uma vizinhança ótima (proximidade ao Rio Tejo e a dois pontos turísticos belíssimos, a Torre de Belém e o Mosteiro do Jerônimos, além de pontos de transporte público a menos de um minuto. Observamos como ponto negativo, mas que não desmerece de maneira alguma o apartamento, a entrada do prédio que apresenta uma escada estreita e com iluminação deficiente. Sem mais, qualificamos positivamente o local, a disponibilidade do anfitrião e a estrutura do apartamento para um casal, foi uma ótima escolha.\r<br/>\r<br/>Recomendamos esta estadia!",Lisboa,pt,"Estivemos em Lisboa por aproximadamente - três - meses. Durante o período, Bruno se mostrou um excelente anfitrião, bastante solícito e resolutivo, nos atendendo prontamente. O apartamento é aconchegante e dispôs do que precisávamos, ou seja, correspondeu todas as nossas expectativas. O apartamento é muito bem localizado, tendo uma vizinhança ótima - proximidade ao Rio Tejo e a dois pontos turísticos belíssimos, a Torre de Belém e o Mosteiro do Jerônimos, além de pontos de transporte público a menos de um minuto. Observamos como ponto negativo, mas que não desmerece de maneira alguma o apartamento, a entrada do prédio que apresenta uma escada estreita e com iluminação deficiente. Sem mais, qualificamos positivamente o local, a disponibilidade do anfitrião e a estrutura do apartamento para um casal, foi uma ótima escolha. Recomendamos esta estadia!"
20,6499,176711099,2017-07-31,27996038,Marilia,"Ótima estadia!! Localização excelente em Belém, próximo aos locais turísticos. Restaurantes próximos agradáveis. Muito próximo a pontos de ônibus e trem.<br/>Apartamento espaçoso, agradável.<br/>Recomendo.",Lisboa,pt,"Ótima estadia! ! Localização excelente em Belém, próximo aos locais turísticos. Restaurantes próximos agradáveis. Muito próximo a pontos de ônibus e trem. Apartamento espaçoso, agradável. Recomendo."
27,6499,508732006,2019-08-13,269570278,Carlos Eduardo,"Bem localizado, área tranquila. Próximo a restaurantes e cafeteria. Casa antiga, bem cuidada e confortável. <br/>Só atenção para o fato que há um lance de escadas bem íngreme para chegar ao apartamento, mas nada incômodo. <br/>Anfitrião muito prestativo.",Lisboa,pt,"Bem localizado, área tranquila. Próximo a restaurantes e cafeteria. Casa antiga, bem cuidada e confortável. Só atenção para o fato que há um lance de escadas bem íngreme para chegar ao apartamento, mas nada incômodo. Anfitrião muito prestativo."
37,6499,587695334,2020-01-03,33688524,Thiago,"Ótimo apartamento, ótimo localização, um ótimo lugar para ficar em sua viagem.<br/>Recomendo a todos 😉",Lisboa,pt,"Ótimo apartamento, ótimo localização, um ótimo lugar para ficar em sua viagem. Recomendo a todos 😉"
46,6499,582305353318129323,2022-03-14,144184697,Atair,"apartamento muito pequeno, banheiro impossível de se usar, não tem Box , chuveiro nãocabe uma pessoa de 1,75 MTpara banho, muito sujo, vizinha moradora, que reclama sobre o abrir e fechar a porta, pois não tem laje, não tema geladeira conforme imagem no Airbnb. infelizmente não vale o que se cobra, localizado em um Excelente lugar.",Lisboa,pt,"apartamento muito pequeno, banheiro impossível de se usar, não tem Box , chuveiro nãocabe uma pessoa de , MTpara banho, muito sujo, vizinha moradora, que reclama sobre o abrir e fechar a porta, pois não tem laje, não tema geladeira conforme imagem no Airbnb. infelizmente não vale o que se cobra, localizado em um Excelente lugar."
50,6499,660709886387398735,2022-06-30,35706228,Garrido,"Apartamento com ótima localização.<br/>Prédio antigo. 2º andar, sem elevador e com escadas antigas e altas.<br/>Casa de banho e cozinha bastante pequenas.<br/>Quarto e sala bons, embora com mesa da sala demasiado pequena.",Lisboa,pt,"Apartamento com ótima localização. Prédio antigo. º andar, sem elevador e com escadas antigas e altas. Casa de banho e cozinha bastante pequenas. Quarto e sala bons, embora com mesa da sala demasiado pequena."
51,6499,662825506128460700,2022-07-03,191238094,Tó,"A localização é excelente e nas redondezas encontra tudo o que necessita (restaurantes, lojas, supermercado, etc.).<br/>O anfitrião é bastante acessível, prestável e simpático.",Lisboa,pt,"A localização é excelente e nas redondezas encontra tudo o que necessita - restaurantes, lojas, supermercado, etc. - . O anfitrião é bastante acessível, prestável e simpático."
52,6499,667887129727775219,2022-07-10,146776261,Florine,O apartamento esta muito bem situado e passamos 4 dias optimos. Fomos muito bem recebidos e aconselhados. Recomendo mesmo ! Obrigada pela estadia e ate à proxima.,Lisboa,pt,O apartamento esta muito bem situado e passamos dias optimos. Fomos muito bem recebidos e aconselhados. Recomendo mesmo ! Obrigada pela estadia e ate à proxima.
65,291676,439125266,2019-04-18,79532783,Maria Etelvina,"O espaço é ótimo, muito bem localizado e o acolhimento é muito bom. Recomendo a quem desejar ficar em Lisboa, no Bairro Alto, este espaço.",Lisboa,pt,"O espaço é ótimo, muito bem localizado e o acolhimento é muito bom. Recomendo a quem desejar ficar em Lisboa, no Bairro Alto, este espaço."
159,6499,881040792406111800,2023-04-30,164442666,Lucinda,"A localização é muita boa, adorei ficar em Belém!! Na rua do apartamento tem condução pública para todos os pontos de Lisboa e comboio próximo para ir para Cascais.<br/>O atendimento foi realizado pelo João e foi excelente!!<br/>Aspecto a melhor, não tinha quase talheres no apto, as facas não cortavam, por exemplo.<br/>Em relação a cortina do box era muito ruim (cabia facilmente um box) <br/>No geral a estadia foi boa",Lisboa,pt,"A localização é muita boa, adorei ficar em Belém! ! Na rua do apartamento tem condução pública para todos os pontos de Lisboa e comboio próximo para ir para Cascais. O atendimento foi realizado pelo João e foi excelente! ! Aspecto a melhor, não tinha quase talheres no apto, as facas não cortavam, por exemplo. Em relação a cortina do box era muito ruim - cabia facilmente um box - No geral a estadia foi boa"
160,6499,903529428461859066,2023-05-31,492702963,Leticia Gonçalves,"Tive alguns problemas com o banheiro. A cortina não segura tudo e cada banho o banheiro alagava. Mas a localização era a que eu precisava, o anfitrião sempre esteve à disposição, apartamento equipado. Sem grandes transtornos.",Lisboa,pt,"Tive alguns problemas com o banheiro. A cortina não segura tudo e cada banho o banheiro alagava. Mas a localização era a que eu precisava, o anfitrião sempre esteve à disposição, apartamento equipado. Sem grandes transtornos."
189,6499,1320938296429559311,2024-12-27,553559079,Vicente,"Sem dúvida que a localização é muito boa, próximo aos principais pontos turísticos de Belém e centro de Lisboa, apresentando restaurantes e transportes de fácil acesso. Mas o apartamento apresenta improvisos e falta de manutenção nas instalações. O banheiro é praticamente dentro da cozinha, que são bem pequenos e encontramos vários utensílios domésticos sujos. Também, observamos que ocorriam vazamentos constantes de água na cozinha.",Lisboa,pt,"Sem dúvida que a localização é muito boa, próximo aos principais pontos turísticos de Belém e centro de Lisboa, apresentando restaurantes e transportes de fácil acesso. Mas o apartamento apresenta improvisos e falta de manutenção nas instalações. O banheiro é praticamente dentro da cozinha, que são bem pequenos e encontramos vários utensílios domésticos sujos. Também, observamos que ocorriam vazamentos constantes de água na cozinha."
191,6499,1367417699450628947,2025-03-01,669431051,Ligia,"Foi uma estadia fantástica, sem nada apontar.<br/>Com certeza se tiver outra oportunidade irei voltar. Muito obrigada e até uma próxima.",Lisboa,pt,"Foi uma estadia fantástica, sem nada apontar. Com certeza se tiver outra oportunidade irei voltar. Muito obrigada e até uma próxima."
204,6499,1502119071495783570,2025-09-03,22446045,Andreia,"O apartamento fica localizado numa rua principal de Belém, em Lisboa. Os arredores são ótimos para dar uma caminhada à beira rio, com tranquilidade e segurança. Para chegar ao apartamento tem umas escadas (como explica no anúncio) que pode dificultar pessoas com mobilidade reduzida. No nosso caso não foi problema. O interior do apartamento é como descrito no anúncio e nas fotos. Ótimo para a estadia de 2-3 pessoas. Com todas as comodidades necessárias para uma boa estadia. A única coisa que foi menos positiva foi o barulho durante a noite. Como o apartamento fica na rua principal, ouve-se o barulho do elétrico, dos autocarros e das pessoas que passam na rua. Mas de resto correu tudo como esperado. O anfitrião foi sempre solícito e respondeu com rapidez, com flexibilidade tanto no check-in como no check-out. Recomendo apesar destas pequenas particularidades.",Lisboa,pt,"O apartamento fica localizado numa rua principal de Belém, em Lisboa. Os arredores são ótimos para dar uma caminhada à beira rio, com tranquilidade e segurança. Para chegar ao apartamento tem umas escadas - como explica no anúncio - que pode dificultar pessoas com mobilidade reduzida. No nosso caso não foi problema. O interior do apartamento é como descrito no anúncio e nas fotos. Ótimo para a estadia de - pessoas. Com todas as comodidades necessárias para uma boa estadia. A única coisa que foi menos positiva foi o barulho durante a noite. Como o apartamento fica na rua principal, ouve-se o barulho do elétrico, dos autocarros e das pessoas que passam na rua. Mas de resto correu tudo como esperado. O anfitrião foi sempre solícito e respondeu com rapidez, com flexibilidade tanto no check-in como no check-out. Recomendo apesar destas pequenas particularidades."
232,25659,32823122,2015-05-22,13393557,Luciane,"O apartamento é muito gostoso, bem arejado e tem tudo o que se precisa. Cozinhamos e lavamos nossas roupas como se estivéssemos em casa. A única dificuldade por causa da bagagem são as escadas íngremes. Mas todo o resto vale a pena. A proprietária nos mandou dicas de Lisboa assim que reservamos para que pudéssemos nos programar. E sua administradora esteve sempre disponível para nos ajudar no que fosse preciso. Obrigada as duas. Passamos dias agradáveis em seu flat.",Lisboa,pt,"O apartamento é muito gostoso, bem arejado e tem tudo o que se precisa. Cozinhamos e lavamos nossas roupas como se estivéssemos em casa. A única dificuldade por causa da bagagem são as escadas íngremes. Mas todo o resto vale a pena. A proprietária nos mandou dicas de Lisboa assim que reservamos para que pudéssemos nos programar. E sua administradora esteve sempre disponível para nos ajudar no que fosse preciso. Obrigada as duas. Passamos dias agradáveis em seu flat."

In [35]:
# ==========================================
# Salvando o DataFrame pré-processado para Lisboa, e criando uma cópia de segurança
# ==========================================
df_Lisboa_pt.to_pickle("Reviews_Lisboa_texto_limpo.pkl")

---------------------
##  **Fazer a junção dos datasets, Rio de Janeiro e Lisboa**
------------

###  Balanceamento dos datasets em (50% / 50%), com base na coluna **'cidade'**, sendo:

- **Rio de Janeiro:** 100.000 entradas
- **Lisboa:** 100.000 entradas

------------

In [36]:
# ==========================================
# Carregar os datasets processados
# ==========================================
df_RJ_concat = pd.read_pickle("Reviews_RJ_texto_limpo.pkl")
df_Lisboa_concat = pd.read_pickle("Reviews_Lisboa_texto_limpo.pkl")

# ==========================================
# Verificar o tamanho dos datasets
# ==========================================
print("RJ:", len(df_RJ_concat))
print("Lisboa:", len(df_Lisboa_concat))

# ==========================================
# Definir o tamanho de balanceamento
# ==========================================
n_amostra = 100000

# ==========================================
# Subamostragem sem duplicar texto
# ==========================================
df_RJ_bal = df_RJ_concat.sample(n=n_amostra, random_state=42)
df_Lisboa_bal = df_Lisboa_concat.sample(n=n_amostra, random_state=42)

# ==========================================
# Concatenar os dois conjuntos balanceados
# ==========================================
df_balancear = pd.concat([df_RJ_bal, df_Lisboa_bal], ignore_index=True)

RJ: 721089
Lisboa: 124783

In [37]:
# ==========================================
# Contar entradas por cidade após o balanceamento de dados
# ==========================================
df_balancear['cidade'].value_counts()

cidade
Rio de Janeiro    100000
Lisboa            100000
Name: count, dtype: int64

In [38]:
# ==========================================
# Conferir dataset
# ==========================================
df_balancear.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments,cidade,lang,texto_limpo
0,1241990244433390890,1450109880518848792,2025-06-23,339707612,Iara,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada",Rio de Janeiro,pt,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada"
1,30938466,617993232260012422,2022-05-02,112589718,Jeison,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje .<br/>Vou falar 4 coisas que não poderia deixar passar.<br/>01- A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional.<br/>02- A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça.<br/>03- A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas.<br/>04- A localização do apartamento é fantástica pois fica pórximo a tudo.<br/>Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico !!!",Rio de Janeiro,pt,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje . Vou falar coisas que não poderia deixar passar. - A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional. - A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça. - A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas. - A localização do apartamento é fantástica pois fica pórximo a tudo. Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico ! ! !"
2,1279989569850103457,1490668744495176611,2025-08-18,12329668,Beatriz,"o apt do Maurício é otimo!!! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca",Rio de Janeiro,pt,"o apt do Maurício é otimo! ! ! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca"
3,1079929507092661295,1147883300514198966,2024-05-02,574751517,Gabriela,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo.",Rio de Janeiro,pt,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo."
4,572381918951779336,1247881696472392123,2024-09-17,172437167,Anna Paula,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!",Rio de Janeiro,pt,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!"

In [40]:
df_balancear.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     200000 non-null  int64
 1   id             200000 non-null  int64
 2   date           200000 non-null  str
 3   reviewer_id    200000 non-null  int64
 4   reviewer_name  199998 non-null  str
 5   comments       200000 non-null  str
 6   cidade         200000 non-null  str
 7   lang           200000 non-null  str
 8   texto_limpo    200000 non-null  str
dtypes: int64(3), str(6)
memory usage: 54.8 MB

In [42]:
# ==========================================
# Remover várias colunas
# ==========================================
df_balancear = df_balancear.drop(columns=['id', 'listing_id', 'reviewer_id', 'reviewer_name'])
df_balancear.head()

,date,comments,cidade,lang,texto_limpo
0,2025-06-23,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada",Rio de Janeiro,pt,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada"
1,2022-05-02,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje .<br/>Vou falar 4 coisas que não poderia deixar passar.<br/>01- A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional.<br/>02- A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça.<br/>03- A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas.<br/>04- A localização do apartamento é fantástica pois fica pórximo a tudo.<br/>Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico !!!",Rio de Janeiro,pt,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje . Vou falar coisas que não poderia deixar passar. - A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional. - A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça. - A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas. - A localização do apartamento é fantástica pois fica pórximo a tudo. Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico ! ! !"
2,2025-08-18,"o apt do Maurício é otimo!!! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca",Rio de Janeiro,pt,"o apt do Maurício é otimo! ! ! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca"
3,2024-05-02,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo.",Rio de Janeiro,pt,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo."
4,2024-09-17,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!",Rio de Janeiro,pt,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!"

In [43]:
# ==========================================
# Salvar o dataset balanceado de Lisboa e Rio de Janeiro, para uso posterior
# ==========================================
df_balancear.to_pickle("Reviews_Lisboa_RJ_200k_texto_limpo.pkl")
print("Dataset balanceado com o texto limpo, salvo com sucesso!")

Dataset balanceado com o texto limpo, salvo com sucesso!

-------------
## Verifificando se os dois datasets (Modelacao de topicos e Analise de sentimento) sao iguais
-------------

In [18]:
df_topics = pd.read_pickle('Reviews_Lisboa_RJ_200k.pkl')
df_topics.head()

,date,comments,cidade,lang,char_count,word_count,texto_limpo,nomes_proprios,texto_anonimizado,texto_normalizado,texto_lematizado
0,2025-06-23,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada",Rio de Janeiro,pt,217,35,Os anfitriões são maravilhosos a casa é um charme com macaquinhos vindo toda manhã na varanda porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada,[],Os anfitriões são maravilhosos a casa é um charme com macaquinhos vindo toda manhã na varanda porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada,os anfitriões são maravilhosos a casa é um charme com macaquinhos vindo toda manhã na varanda porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada,anfitrião maravilhoso casa charme macaquinho manhã varanda considerar móvel velho objeto pessoal acabar ficar cheiro forte guardar fechar
1,2022-05-02,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje .<br/>Vou falar 4 coisas que não poderia deixar passar.<br/>01- A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional.<br/>02- A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça.<br/>03- A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas.<br/>04- A localização do apartamento é fantástica pois fica pórximo a tudo.<br/>Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico !!!",Rio de Janeiro,pt,751,128,A estadia com o Renato foi a melhor experiência no Airbnb até hoje Vou falar coisas que não poderia deixar passar A vista da cobertura é sensacional um ângulo de visão da Bahia de Guanabara Pão de Açucar Aeroporto Santos Dumont e Cristo Redentor é sensacional A recepção no Chek in foi indescritível fomos recebidos com algumas surpresas que me deixaram de queixo caído uma delas é de uma simpatia sem igual mas não posso contar a vocês porque perderia a graça A flexibilidade na reserva e as dicas do RJ que o Renato passa são maravilhosas A localização do apartamento é fantástica pois fica pórximo a tudo Enfim Super indico o Renato para se hospedarem o Apartamento é fantastico,"[Renato, Renato, Renato]",A estadia com o host_anfitriao foi a melhor experiência no Airbnb até hoje Vou falar coisas que não poderia deixar passar A vista da cobertura é sensacional um ângulo de visão da Bahia de Guanabara Pão de Açucar Aeroporto Santos Dumont e Cristo Redentor é sensacional A recepção no Chek in foi indescritível fomos recebidos com algumas surpresas que me deixaram de queixo caído uma delas é de uma simpatia sem igual mas não posso contar a vocês porque perderia a graça A flexibilidade na reserva e as dicas do RJ que o host_anfitriao passa são maravilhosas A localização do apartamento é fantástica pois fica pórximo a tudo Enfim Super indico o host_anfitriao para se hospedarem o Apartamento é fantastico,a estadia com o host_anfitriao foi a melhor experiência no airbnb até hoje vou falar coisas que não poderia deixar passar a vista da cobertura é sensacional um ângulo de visão da bahia de guanabara pão de açucar aeroporto santos dumont e cristo redentor é sensacional a recepção no chek in foi indescritível fomos recebidos com algumas surpresas que me deixaram de queixo caído uma delas é de uma simpatia sem igual mas não posso contar a vocês porque perderia a graça a flexibilidade na reserva e as dicas do rj que o host_anfitriao passa são maravilhosas a localização do apartamento é fantástica pois fica pórximo a tudo enfim super indico o host_anfitriao para se hospedarem o apartamento é fantastico,estadia host_anfitriao bom experiência airbnb hoje ir falar coisa poder deixar passar vista cobertura sensacional ângulo visão bahia guanabara pão açucar aeroporto santo dumont cristo redentor sensacional recepção chek in indescritível receber surpresa deixar queixo cair de elas simpatia igual contar perder graça flexibilidade reserva dica rj host_anfitriao passar maravilhoso localização fantástico ficar pórximo enfim super indico host_anfitriao hospedar fantastico
2,2025-08-18,"o apt do Maurício é otimo!!! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca",Rio de Janeiro,pt,184,36,o apt do Maurício é otimo tudo nele nos encantou o prédio os porteiros o apt a gentileza a localização enfim um lugar com a cara do Rio e da gentileza e bom gosto do carioca,[],o apt do Maurício é otimo tudo nele nos encantou o prédio os porteiros o apt a gentileza a localização enfim um lugar com a cara do Rio e da gentileza e bom gosto do carioca,o apartamento do maurício é otimo tudo nele nos encantou o prédio os porteiros o apartamento a gentileza a localização enfim um lugar com a cara do rio e da gentileza e bom gosto do carioca,maurício otimo em ele encantar prédio porteiro gentileza localização enfim cara rio gentileza gosto carioca
3,2024-05-02,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo.",Rio de Janeiro,pt,426,67,muito organizado bonito limpo funcional anfitrião atencioso os melhores horários de check in e checkout que já vi gelo café toalhas roupa de cama tudo que precisei tinha Supermercado e farmácia perto excelente a vila estava um pouco barulhenta a noite mas entendo que isso está fora do controle do anfitrião umica recomendação seria um insulfim espelhado na porta mas pq eu sou mais sensível a claridade mesmo,[],muito organizado bonito limpo funcional anfitrião atencioso os melhores horários de check in e checkout que já vi gelo café toalhas roupa de cama tudo que precisei tinha Supermercado e farmácia perto excelente a vila estava um pouco barulhenta a noite mas entendo que isso está fora do controle do anfitrião umica recomendação seria um insulfim espelhado na porta mas pq eu sou mais sensível a claridade mesmo,muito organizado bonito limpo funcional anfitrião atencioso os melhores horários de check in e checkout que já vi gelo café toalhas roupa de cama tudo que precisei tinha supermercado e farmácia perto excelente a vila estava um pouco barulhenta a noite mas entendo que isso está fora do controle do anfitrião umica recomendação seria um insulfim espelhado na porta mas pq eu sou mais sensível a claridade mesmo,organizar bonito limpo funcional anfitrião atencioso bom horário check in checkout ver gelo café toalha roupa cama precisei ter supermercar farmácia excelente vila barulhentar noite entendar controle anfitrião umico recomendação insulfim espelhar porta pq sensível claridade
4,2024-09-17,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!",Rio de Janeiro,pt,90,12,Incrível Amei tudo Super rápida em soluções e respostas Localização melhor impossível,[Incrível Amei],host_anfitriao tudo Super rápida em soluções e respostas Localização melhor impossível,host_anfitriao tudo super rápida em soluções e respostas localização melhor impossível,host_anfitriao super rápido solução resposta localização bom impossível

In [19]:
df_topics.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   date               200000 non-null  str
 1   comments           200000 non-null  str
 2   cidade             200000 non-null  str
 3   lang               200000 non-null  str
 4   char_count         200000 non-null  int64
 5   word_count         200000 non-null  int64
 6   texto_limpo        200000 non-null  str
 7   nomes_proprios     200000 non-null  object
 8   texto_anonimizado  200000 non-null  str
 9   texto_normalizado  200000 non-null  str
 10  texto_lematizado   200000 non-null  str
dtypes: int64(2), object(1), str(8)
memory usage: 16.8+ MB

In [20]:
df_sent = pd.read_pickle('Reviews_Lisboa_RJ_200k_texto_limpo.pkl')
df_sent.head()

,id,date,comments,cidade,lang,texto_limpo
0,1450109880518848792,2025-06-23,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada",Rio de Janeiro,pt,"Os anfitriões são maravilhosos, a casa é um charme com macaquinhos vindo toda manhã na varanda, porém considerando ter muitos móveis velhos e objetos pessoais acaba ficando com cheiro forte de coisa guardada e fechada"
1,617993232260012422,2022-05-02,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje .<br/>Vou falar 4 coisas que não poderia deixar passar.<br/>01- A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional.<br/>02- A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça.<br/>03- A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas.<br/>04- A localização do apartamento é fantástica pois fica pórximo a tudo.<br/>Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico !!!",Rio de Janeiro,pt,"A estadia com o Renato foi a melhor experiência no Airbnb até hoje . Vou falar 4 coisas que não poderia deixar passar. 01- A vista da cobertura é sensacional , um ângulo de visão da Bahia de Guanabara , Pão de Açucar , Aeroporto Santos Dumont e Cristo Redentor é sensacional. 02- A recepção no Chek-in foi indescritível , fomos recebidos com algumas surpresas que me deixaram de queixo caído , uma delas é de uma simpatia sem igual, mas não posso contar a vocês porque perderia a graça. 03- A flexibilidade na reserva e as dicas do RJ que o Renato passa , são maravilhosas. 04- A localização do apartamento é fantástica pois fica pórximo a tudo. Enfim , Super indico o Renato para se hospedarem , o Apartamento é fantastico ! ! !"
2,1490668744495176611,2025-08-18,"o apt do Maurício é otimo!!! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca",Rio de Janeiro,pt,"o apt do Maurício é otimo! ! ! tudo nele nos encantou. o prédio, os porteiros, o apt, a gentileza, a localização, enfim, um lugar com a cara do Rio e da gentileza e bom gosto do carioca"
3,1147883300514198966,2024-05-02,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo.",Rio de Janeiro,pt,"muito organizado, bonito, limpo, funcional. anfitrião atencioso, os melhores horários de check-in e checkout que já vi. gelo, café, toalhas, roupa de cama tudo que precisei tinha. Supermercado e farmácia perto, excelente. a vila estava um pouco barulhenta a noite, mas entendo que isso está fora do controle do anfitrião. umica recomendação seria um insulfim espelhado na porta. mas pq eu sou mais sensível a claridade mesmo."
4,1247881696472392123,2024-09-17,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!",Rio de Janeiro,pt,"Incrível! Amei tudo. Super rápida em soluções e respostas. Localização melhor, impossível!"

In [21]:
df_sent.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           200000 non-null  int64
 1   date         200000 non-null  str
 2   comments     200000 non-null  str
 3   cidade       200000 non-null  str
 4   lang         200000 non-null  str
 5   texto_limpo  200000 non-null  str
dtypes: int64(1), str(5)
memory usage: 50.3 MB

In [22]:
# 1) Verificar se têm as mesmas colunas
mesmas_colunas = set(df_sent.columns) == set(df_topics.columns)

# 2) Contar o número de linhas
n_linhas_df_sent = df_sent.shape[0]
n_linhas_df_topics = df_topics.shape[0]

# 3) Comparar só as colunas em comum, ignorando o índice
colunas_comuns = ['comments', 'date', 'cidade']

mesmos_dados_comuns = (
    df_sent[colunas_comuns].reset_index(drop=True)
    .equals(df_topics[colunas_comuns].reset_index(drop=True))
)

print("Mesmas colunas:", mesmas_colunas)
print("Número de linhas no df_sent:", n_linhas_df_sent)
print("Número de linhas no df_topics:", n_linhas_df_topics)
print("Mesmos dados nas colunas comuns:", mesmos_dados_comuns)

Mesmas colunas: False
Número de linhas no df_sent: 200000
Número de linhas no df_topics: 200000
Mesmos dados nas colunas comuns: True